
create table "users" (
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR
);


create table "users2" (
	"user_id" INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
	"username" VARCHAR
);

create table "users3" (
	"user_id" INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
	"username" VARCHAR
);

create table "users4" (
	"user_id" INTEGER GENERATED ALWAYS as IDENTITY
	(START WITH 100 INCREMENT by 2),
	"username" VARCHAR
);


create table usersDual(
	id1 int,
	id2 int,
	PRIMARY KEY( id1, id2)
);


CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
--Eliminar
--DROP EXTENSION "uuid-ossp";

SELECT gen_random_uuid(), uuid_generate_v4();

create table users5 (
	"user_id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	"username" VARCHAR
);


DROP SEQUENCE user_sequence;
CREATE SEQUENCE user_sequence;

SELECT nextval('user_sequence'), currval('user_sequence');


create table users6 (
	"user_id" INTEGER PRIMARY KEY DEFAULT nextval('user_sequence'),
	"username" VARRCHAR
)

